Homepage:
    path:     /
    defaults: { _controller: GuigurFrontBundle:Default:index }
Projects:
    path:     /Projects
    defaults: { _controller: GuigurFrontBundle:Project:index }
Project:
    path:     /Project/{nameOfProject}
    defaults: { _controller: GuigurFrontBundle:Project:index }
Portfolio:
    path:     /Portfolio
    defaults: { _controller: GuigurFrontBundle:Portfolio:index }
Archives:
    path:     /Archives
    defaults: { _controller: GuigurFrontBundle:Archives:index }
Blog:
    path:     /Blog
    defaults: { _controller: GuigurFrontBundle:Blog:index }
About:
    path:     /About
    defaults: { _controller: GuigurFrontBundle:About:index }
Shop:
    path:     /Shop
    defaults: { _controller: GuigurFrontBundle:Shop:index }
Contact:
    path:     /Contact
    defaults: { _controller: GuigurFrontBundle:Contact:index }
Random:
    path:     /Random
    defaults: { _controller: GuigurFrontBundle:Random:index }
CV:
    path:     /CV
    defaults: { _controller: GuigurFrontBundle:Cv:index }
LaSuiteDeTed:
    path:     /LaSuiteDeTED
    defaults: { _controller: GuigurFrontBundle:TED:index }
Experiments:
    path:     /Experiments
    defaults: { _controller: GuigurFrontBundle:Experiment:index }
Changelog:
    path:     /Changelog
    defaults: { _controller: GuigurFrontBundle:Changelog:index }