homepage:
    path:     /
    defaults: { _controller: GuigurFrontBundle:Default:index }
Project_all:
    path:     /Project
    defaults: { _controller: GuigurFrontBundle:Project:index }
Project:
    path:     /Project/{nameOfProject}
    defaults: { _controller: GuigurFrontBundle:Project:index }
Blog:
    path:     /Blog
    defaults: { _controller: GuigurFrontBundle:Blog:index }
About:
    path:     /About
    defaults: { _controller: GuigurFrontBundle:About:index }
Shop:
    path:     /Shop
    defaults: { _controller: GuigurFrontBundle:Shop:index }
Contact:
    path:     /Contact
    defaults: { _controller: GuigurFrontBundle:Contact:index }
Troll:
    path:     /Troll
    defaults: { _controller: GuigurFrontBundle:Troll:index }
CV:
    path:     /CV
    defaults: { _controller: GuigurFrontBundle:Cv:index }
LaSuiteDeTed:
    path:     /LaSuiteDeTED
    defaults: { _controller: GuigurFrontBundle:TED:index }
TED:
    path:     /TED
    defaults: { _controller: GuigurFrontBundle:TED:index }