services:
    guigur.catchphrase:
        class: GuigurFrontBundle\Service\CatchPhraseService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    guigur.projects:
        class: GuigurFrontBundle\Service\ProjectsService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    guigur.texts:
        class: GuigurFrontBundle\Service\TextsService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    guigur.imageChecker:
        class: GuigurFrontBundle\Service\ImageCheckerService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    login_listener:
        class: GuigurFrontBundle\Service\LoginListenerService
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@fos_user.user_manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
            - { name: kernel.event_listener, event: security.authentication.failure	, method: onSecurityAuthenticationFailure }

