services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    # ...

    GuigurFrontBundle\Service\CatchPhraseService:

    GuigurFrontBundle\Service\ProjectsService:

    GuigurFrontBundle\Service\TextsService:

    GuigurFrontBundle\Service\ImageCheckerService:
