<?php

namespace GuigurFrontBundle\Repository;

/**
 * CatchPhraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatchPhraseRepository extends \Doctrine\ORM\EntityRepository
{
}
