<?php

namespace GuigurFrontBundle\Repository;

/**
 * ChangeLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
