<?php

namespace GuigurFrontBundle\Repository;

/**
 * cvContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cvContentRepository extends \Doctrine\ORM\EntityRepository
{
}
