<?php

namespace GuigurFrontBundle\Repository;

/**
 * HostingServiceWebsitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostingServiceWebsitesRepository extends \Doctrine\ORM\EntityRepository
{
}
