<?php

namespace GuigurFrontBundle\Repository;

/**
 * JokeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokeRepository extends \Doctrine\ORM\EntityRepository
{
}
