<?php

namespace GuigurFrontBundle\Repository;

/**
 * LinkShortenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkShortenerRepository extends \Doctrine\ORM\EntityRepository
{
}
