<?php

namespace GuigurFrontBundle\Repository;

/**
 * linkShortenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class linkShortenerRepository extends \Doctrine\ORM\EntityRepository
{
}
