<?php

namespace GuigurFrontBundle\Repository;

/**
 * LoginAttemptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginAttemptsRepository extends \Doctrine\ORM\EntityRepository
{
}
