<?php

namespace GuigurFrontBundle\Repository;

/**
 * ProjectsCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
