<?php

namespace BlogGuigurFrontEndBundle\Repository;

/**
 * JokeSmileVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokeSmileVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
