admin_homepage:
    path:     /
    defaults: { _controller: GuigurAdminBundle:Default:index }

admin_visits:
    path:     /visits
    defaults: { _controller: GuigurAdminBundle:Default:visits }

admin_login:
    path:     /login
    defaults: { _controller: GuigurAdminBundle:Default:login }

admin_register:
    path:     /register
    defaults: { _controller: GuigurAdminBundle:Default:register }

admin_texts:
    path:     /texts
    defaults: { _controller: GuigurAdminBundle:Default:texts }

admin_shop:
    path:     /shop
    defaults: { _controller: GuigurAdminBundle:Default:shop }

admin_projects:
    path:     /projects
    defaults: { _controller: GuigurAdminBundle:AdmProject:index }

admin_users:
    path:     /users
    defaults: { _controller: GuigurAdminBundle:AdmUser:index }

admin_download:
    path: /dl/{file}
    defaults: { _controller: GuigurAdminBundle:Default:sendfile }

########################################################################################################################
admin_ajax_project_state_toggle:
    path:     /ajax/project/state/toggle
    defaults: { _controller: GuigurAdminBundle:AdmProject:ajaxStateToggle }