admin_homepage:
    path:     /
    defaults: { _controller: GuigurAdminBundle:Default:index }

admin_visits:
    path:     /Visits
    defaults: { _controller: GuigurAdminBundle:Default:visits }

admin_texts:
    path:     /Texts
    defaults: { _controller: GuigurAdminBundle:Default:texts }

admin_download:
    path: /dl/{file}
    defaults: { _controller: GuigurAdminBundle:Default:sendfile }
