guigur_admin:
    resource: "@GuigurAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

guigur_front:
    resource: "@GuigurFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
