# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  GuigurFrontBundle\Service\LocaleService:
    arguments: ['%kernel.default_locale%']
    # redundant if you're using autoconfigure
    tags: [kernel.event_subscriber]
  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }
