homepage:
    path:     /
    defaults: { _controller: BlogGuigurFrontEndBundle:Default:index }
Blog:
    path:     /Blog
    defaults: { _controller: BlogGuigurFrontEndBundle:Blog:index }
About:
    path:     /About
    defaults: { _controller: BlogGuigurFrontEndBundle:Default:index }
Shop:
    path:     /Shop
    defaults: { _controller: BlogGuigurFrontEndBundle:Default:index }
Contact:
    path:     /Contact
    defaults: { _controller: BlogGuigurFrontEndBundle:Default:index }
Troll:
    path:     /Troll
    defaults: { _controller: BlogGuigurFrontEndBundle:Default:troll }

CV:
    path:     /CV
    defaults: { _controller: BlogGuigurFrontEndBundle:Cv:index }